package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 13, 2017 1:43:12 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Deliverable generated by hbm2java
 */
public class Deliverable implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 1756645330425186871L;


  @Expose
  private Long id;


  @Expose
  private User modifiedBy;


  @Expose
  private User createdBy;


  @Expose
  private ProjectStatus projectStatus;


  @Expose
  private Project project;


  @Expose
  private DeliverableType deliverableType;


  @Expose
  private String name;


  @Expose
  private Date startDate;


  @Expose
  private Date endDate;


  @Expose
  private boolean active;

  @Expose
  private Date activeSince;


  @Expose
  private Date dateCreated;


  @Expose
  private String modificationJustification;


  @Expose
  private DeliverableCrosscutingTheme deliverableCrosscutingTheme;

  private Set<DeliverableOutput> deliverableOutputs = new HashSet<DeliverableOutput>(0);

  private Set<SectionStatus> sectionStatuses = new HashSet<SectionStatus>(0);

  private Set<DeliverableDocument> deliverableDocuments = new HashSet<DeliverableDocument>(0);

  private List<DeliverableDocument> documents;

  private List<DeliverableOutput> outputs;


  public Deliverable() {
  }

  public Deliverable(Project project, boolean active) {
    this.project = project;
    this.active = active;
  }


  public Deliverable(User modifiedBy, User createdBy, ProjectStatus projectStatus, Project project,
    DeliverableType deliverableType, String name, Date startDate, Date endDate, boolean active, Date activeSince,
    String modificationJustification) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.projectStatus = projectStatus;
    this.project = project;
    this.deliverableType = deliverableType;
    this.name = name;
    this.startDate = startDate;
    this.endDate = endDate;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    Deliverable other = (Deliverable) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public Date getDateCreated() {
    return dateCreated;
  }

  public DeliverableCrosscutingTheme getDeliverableCrosscutingTheme() {
    return deliverableCrosscutingTheme;
  }

  public Set<DeliverableDocument> getDeliverableDocuments() {
    return deliverableDocuments;
  }

  public Set<DeliverableOutput> getDeliverableOutputs() {
    return deliverableOutputs;
  }

  public DeliverableType getDeliverableType() {
    return deliverableType;
  }

  public List<DeliverableDocument> getDocuments() {
    return documents;
  }

  public Date getEndDate() {
    return endDate;
  }

  @Override
  public Long getId() {
    return id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public String getModificationJustification() {
    return modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public String getName() {
    return name;
  }

  public List<DeliverableOutput> getOutputs() {
    return outputs;
  }

  public Project getProject() {
    return project;
  }


  public ProjectStatus getProjectStatus() {
    return projectStatus;
  }


  public Set<SectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }


  public Date getStartDate() {
    return startDate;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setDateCreated(Date dateCreated) {
    this.dateCreated = dateCreated;
  }


  public void setDeliverableCrosscutingTheme(DeliverableCrosscutingTheme deliverableCrosscutingTheme) {
    this.deliverableCrosscutingTheme = deliverableCrosscutingTheme;
  }

  public void setDeliverableDocuments(Set<DeliverableDocument> deliverableDocuments) {
    this.deliverableDocuments = deliverableDocuments;
  }

  public void setDeliverableOutputs(Set<DeliverableOutput> deliverableOutputs) {
    this.deliverableOutputs = deliverableOutputs;
  }

  public void setDeliverableType(DeliverableType deliverableType) {
    this.deliverableType = deliverableType;
  }

  public void setDocuments(List<DeliverableDocument> documents) {
    this.documents = documents;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setOutputs(List<DeliverableOutput> outputs) {
    this.outputs = outputs;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public void setProjectStatus(ProjectStatus projectStatus) {
    this.projectStatus = projectStatus;
  }


  public void setSectionStatuses(Set<SectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


}

