package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 16, 2017 9:21:01 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * MonitoringOutcome generated by hbm2java
 */
public class MonitoringOutcome implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 6260380573367662563L;

  @Expose
  private Long id;


  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;


  @Expose
  private ResearchOutcome researchOutcome;


  @Expose
  private int year;


  @Expose
  private String narrative;

  @Expose
  private boolean active;


  @Expose
  private Date activeSince;


  @Expose
  private String modificationJustification;


  private Set<MonitoringMilestone> monitoringMilestones = new HashSet<MonitoringMilestone>(0);

  private List<MonitoringMilestone> milestones;

  private Set<MonitorignOutcomeEvidence> monitorignOutcomeEvidences = new HashSet<MonitorignOutcomeEvidence>(0);

  private List<MonitorignOutcomeEvidence> evidences;

  public MonitoringOutcome() {
  }

  public MonitoringOutcome(ResearchOutcome researchOutcome, int year, boolean active) {
    this.researchOutcome = researchOutcome;
    this.year = year;
    this.active = active;
  }

  public MonitoringOutcome(User modifiedBy, User createdBy, ResearchOutcome researchOutcome, int year, String narrative,
    boolean active, Date activeSince, String modificationJustification) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.researchOutcome = researchOutcome;
    this.year = year;
    this.narrative = narrative;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public List<MonitorignOutcomeEvidence> getEvidences() {
    return evidences;
  }

  @Override
  public Long getId() {
    return id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public List<MonitoringMilestone> getMilestones() {
    return milestones;
  }

  public String getModificationJustification() {
    return modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public Set<MonitorignOutcomeEvidence> getMonitorignOutcomeEvidences() {
    return monitorignOutcomeEvidences;
  }


  public Set<MonitoringMilestone> getMonitoringMilestones() {
    return monitoringMilestones;
  }


  public String getNarrative() {
    return narrative;
  }


  public ResearchOutcome getResearchOutcome() {
    return researchOutcome;
  }


  public int getYear() {
    return year;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public List<MonitoringMilestone> monitoringMilestones() {
    return milestones;
  }


  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setEvidences(List<MonitorignOutcomeEvidence> evidences) {
    this.evidences = evidences;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setMilestones(List<MonitoringMilestone> milestones) {
    this.milestones = milestones;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setMonitorignOutcomeEvidences(Set<MonitorignOutcomeEvidence> monitorignOutcomeEvidences) {
    this.monitorignOutcomeEvidences = monitorignOutcomeEvidences;
  }


  public void setMonitoringMilestones(Set<MonitoringMilestone> monitoringMilestones) {
    this.monitoringMilestones = monitoringMilestones;
  }


  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public void setResearchOutcome(ResearchOutcome researchOutcome) {
    this.researchOutcome = researchOutcome;
  }

  public void setYear(int year) {
    this.year = year;
  }


}

