package org.cgiar.ccafs.marlo.data.model;
// Generated Nov 30, 2016 9:52:32 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * NextuserType generated by hbm2java
 */
public class NextuserType implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -4356098204290324921L;


  @Expose
  private Long id;


  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;
  @Expose
  private NextuserType nextuserType;
  @Expose
  private String name;
  @Expose
  private Date activeSince;
  @Expose
  private boolean active;
  @Expose
  private String modificationJustification;
  private Set<NextuserType> nextuserTypes = new HashSet<NextuserType>(0);
  private Set<ResearchOutputsNextUser> researchOutputsNextUsers = new HashSet<ResearchOutputsNextUser>(0);

  public NextuserType() {
  }

  public NextuserType(String name) {
    this.name = name;
  }


  public NextuserType(User modifiedBy, User createdBy, NextuserType nextuserType, String name, Date activeSince,
    boolean active, String modificationJustification, Set<NextuserType> nextuserTypes,
    Set<ResearchOutputsNextUser> researchOutputsNextUsers) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.nextuserType = nextuserType;
    this.name = name;
    this.activeSince = activeSince;
    this.active = active;
    this.modificationJustification = modificationJustification;
    this.nextuserTypes = nextuserTypes;
    this.researchOutputsNextUsers = researchOutputsNextUsers;
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    NextuserType other = (NextuserType) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getName() {
    return name;
  }


  public NextuserType getNextuserType() {
    return nextuserType;
  }

  public Set<NextuserType> getNextuserTypes() {
    return nextuserTypes;
  }

  public Set<ResearchOutputsNextUser> getResearchOutputsNextUsers() {
    return researchOutputsNextUsers;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setName(String name) {
    this.name = name;
  }


  public void setNextuserType(NextuserType nextuserType) {
    this.nextuserType = nextuserType;
  }

  public void setNextuserTypes(Set<NextuserType> nextuserTypes) {
    this.nextuserTypes = nextuserTypes;
  }


  public void setResearchOutputsNextUsers(Set<ResearchOutputsNextUser> researchOutputsNextUsers) {
    this.researchOutputsNextUsers = researchOutputsNextUsers;
  }


}

