package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 28, 2017 11:23:33 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ProjectFundingSource generated by hbm2java
 */
public class ProjectFundingSource implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 738010291598228873L;

  @Expose
  private Integer id;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private FundingSourceType fundingSourceType;

  @Expose
  private Project project;

  @Expose
  private String donor;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;


  public ProjectFundingSource() {
  }


  public ProjectFundingSource(FundingSourceType fundingSourceType, Project project, String donor, boolean active) {
    this.fundingSourceType = fundingSourceType;
    this.project = project;
    this.donor = donor;
    this.active = active;
  }


  public ProjectFundingSource(User modifiedBy, User createdBy, FundingSourceType fundingSourceType, Project project,
    String donor, boolean active, Date activeSince, String modificationJustification) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.fundingSourceType = fundingSourceType;
    this.project = project;
    this.donor = donor;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public String getDonor() {
    return donor;
  }


  public FundingSourceType getFundingSourceType() {
    return fundingSourceType;
  }


  @Override
  public Integer getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public String getModificationJustification() {
    return modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public Project getProject() {
    return project;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setDonor(String donor) {
    this.donor = donor;
  }

  public void setFundingSourceType(FundingSourceType fundingSourceType) {
    this.fundingSourceType = fundingSourceType;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setProject(Project project) {
    this.project = project;
  }

}

