package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 28, 2017 11:24:30 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ProjectPartnerPerson generated by hbm2java
 */
public class ProjectPartnerPerson implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -5721682159549693547L;

  @Expose
  private Long id;

  @Expose
  private User userId;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private ProjectPartner projectPartner;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;


  public ProjectPartnerPerson() {
  }


  public ProjectPartnerPerson(boolean active) {
    this.active = active;
  }


  public ProjectPartnerPerson(User userId, User modifiedBy, User createdBy, ProjectPartner projectPartner,
    boolean active, Date activeSince, String modificationJustification) {
    this.userId = userId;
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.projectPartner = projectPartner;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getModificationJustification() {
    return modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public ProjectPartner getProjectPartner() {
    return projectPartner;
  }

  public User getUserId() {
    return userId;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setProjectPartner(ProjectPartner projectPartner) {
    this.projectPartner = projectPartner;
  }


  public void setUserId(User userId) {
    this.userId = userId;
  }


}

