package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 28, 2017 11:24:30 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ProjectPartner generated by hbm2java
 */
public class ProjectPartner implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -564182537522358471L;

  @Expose
  private Long id;


  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private Institution institution;

  @Expose
  private Project project;

  @Expose
  private boolean internal;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;

  private Set<ProjectPartnerPerson> projectPartnerPersons = new HashSet<ProjectPartnerPerson>(0);

  private List<ProjectPartnerPerson> users;

  public ProjectPartner() {
  }

  public ProjectPartner(Institution institution, Project project, boolean active) {
    this.institution = institution;
    this.project = project;
    this.active = active;
  }

  public ProjectPartner(User modifiedBy, User createdBy, Institution institution, Project project, boolean internal,
    boolean active, Date activeSince, String modificationJustification,
    Set<ProjectPartnerPerson> projectPartnerPersons) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.institution = institution;
    this.project = project;
    this.internal = internal;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
    this.projectPartnerPersons = projectPartnerPersons;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectPartner other = (ProjectPartner) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Long getId() {
    return id;
  }


  public Institution getInstitution() {
    return institution;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public Project getProject() {
    return project;
  }


  public Set<ProjectPartnerPerson> getProjectPartnerPersons() {
    return projectPartnerPersons;
  }


  public List<ProjectPartnerPerson> getUsers() {
    return users;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public boolean isInternal() {
    return internal;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setInstitution(Institution institution) {
    this.institution = institution;
  }

  public void setInternal(boolean internal) {
    this.internal = internal;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setProject(Project project) {
    this.project = project;
  }

  public void setProjectPartnerPersons(Set<ProjectPartnerPerson> projectPartnerPersons) {
    this.projectPartnerPersons = projectPartnerPersons;
  }


  public void setUsers(List<ProjectPartnerPerson> users) {
    this.users = users;
  }

}

