package org.cgiar.ccafs.marlo.data.model;
// Generated Nov 23, 2016 11:30:56 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ResearchOutputPartnerPerson generated by hbm2java
 */
public class ResearchOutputPartnerPerson implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 7878374433525614391L;

  @Expose
  private Integer id;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private ResearchOutputPartner researchOutputPartner;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;


  public ResearchOutputPartnerPerson() {
  }


  public ResearchOutputPartnerPerson(User modifiedBy, User createdBy, ResearchOutputPartner researchOutputPartner,
    boolean active, Date activeSince) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.researchOutputPartner = researchOutputPartner;
    this.active = active;
    this.activeSince = activeSince;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Integer getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public ResearchOutputPartner getResearchOutputPartner() {
    return researchOutputPartner;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setResearchOutputPartner(ResearchOutputPartner researchOutputPartner) {
    this.researchOutputPartner = researchOutputPartner;
  }


}

