package org.cgiar.ccafs.marlo.data.model;
// Generated Nov 23, 2016 11:30:56 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ResearchOutputPartnerPerson generated by hbm2java
 */
public class ResearchOutputPartnerPerson implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 7878374433525614391L;


  @Expose
  private Long id;


  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;


  @Expose
  private ResearchOutputPartner researchOutputPartner;


  @Expose
  private boolean active;


  @Expose
  private Date activeSince;

  @Expose
  private User user;

  public ResearchOutputPartnerPerson() {
  }

  public ResearchOutputPartnerPerson(User modifiedBy, User createdBy, ResearchOutputPartner researchOutputPartner,
    boolean active, Date activeSince) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.researchOutputPartner = researchOutputPartner;
    this.active = active;
    this.activeSince = activeSince;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ResearchOutputPartnerPerson other = (ResearchOutputPartnerPerson) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public ResearchOutputPartner getResearchOutputPartner() {
    return researchOutputPartner;
  }


  public User getUser() {
    return user;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setResearchOutputPartner(ResearchOutputPartner researchOutputPartner) {
    this.researchOutputPartner = researchOutputPartner;
  }


  public void setUser(User user) {
    this.user = user;
  }


}

