package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 2, 2016 11:02:00 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchCycle generated by hbm2java
 */
public class ResearchCycle implements java.io.Serializable {


  private static final long serialVersionUID = -8464775969513955058L;


  private Long id;


  private User modifiedBy;


  private User createdBy;


  private String name;


  private String acronym;


  private boolean active;


  private String modificationJustification;


  private Date activeSince;


  private Set<Submission> submissions = new HashSet<Submission>(0);


  public ResearchCycle() {
  }


  public ResearchCycle(boolean active) {
    this.active = active;
  }


  public ResearchCycle(User modifiedBy, User createdBy, String name, String acronym, boolean active,
    String modificationJustification, Date activeSince, Set<Submission> submissions) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.name = name;
    this.acronym = acronym;
    this.active = active;
    this.modificationJustification = modificationJustification;
    this.activeSince = activeSince;
    this.submissions = submissions;
  }


  public String getAcronym() {
    return acronym;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public Long getId() {
    return id;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public User getModifiedBy() {
    return modifiedBy;
  }

  public String getName() {
    return name;
  }

  public Set<Submission> getSubmissions() {
    return submissions;
  }

  public boolean isActive() {
    return active;
  }

  public void setAcronym(String acronym) {
    this.acronym = acronym;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setName(String name) {
    this.name = name;
  }

  public void setSubmissions(Set<Submission> submissions) {
    this.submissions = submissions;
  }

}

