package org.cgiar.ccafs.marlo.data.model;
// Generated Nov 30, 2016 9:52:32 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ResearchOutputsNextUser generated by hbm2java
 */
public class ResearchOutputsNextUser implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 4282051161983708196L;

  @Expose
  private Long id;

  @Expose
  private ResearchOutput researchOutput;

  @Expose
  private NextuserType nextuserType;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private Date activeSince;

  @Expose
  private boolean active;

  @Expose
  private String modificationJustification;


  public ResearchOutputsNextUser() {
  }


  public ResearchOutputsNextUser(ResearchOutput researchOutput, NextuserType nextuserType) {
    this.researchOutput = researchOutput;
    this.nextuserType = nextuserType;
  }


  public ResearchOutputsNextUser(ResearchOutput researchOutput, NextuserType nextuserType, User modifiedBy,
    User createdBy, Date activeSince, boolean active, String modificationJustification) {
    this.researchOutput = researchOutput;
    this.nextuserType = nextuserType;
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.activeSince = activeSince;
    this.active = active;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public NextuserType getNextuserType() {
    return nextuserType;
  }

  public ResearchOutput getResearchOutput() {
    return researchOutput;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setNextuserType(NextuserType nextuserType) {
    this.nextuserType = nextuserType;
  }


  public void setResearchOutput(ResearchOutput researchOutput) {
    this.researchOutput = researchOutput;
  }

}

