package org.cgiar.ccafs.marlo.data.model;
// Generated May 31, 2017 4:03:52 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * SrfIdo generated by hbm2java
 */
public class SrfIdo implements java.io.Serializable {


  private static final long serialVersionUID = -2164682587700175677L;


  private Long id;


  private User modifiedBy;


  private User createdBy;


  private SrfCrossCuttingIssue srfCrossCuttingIssue;


  private String description;


  private boolean crossCutting;


  private boolean active;


  private Date activeSince;


  private String modificationJustification;


  public SrfIdo() {
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public String getDescription() {
    return description;
  }


  public Long getId() {
    return id;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public User getModifiedBy() {
    return modifiedBy;
  }


  public SrfCrossCuttingIssue getSrfCrossCuttingIssue() {
    return srfCrossCuttingIssue;
  }

  public boolean isActive() {
    return active;
  }

  public boolean isCrossCutting() {
    return crossCutting;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setCrossCutting(boolean crossCutting) {
    this.crossCutting = crossCutting;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setSrfCrossCuttingIssue(SrfCrossCuttingIssue srfCrossCuttingIssue) {
    this.srfCrossCuttingIssue = srfCrossCuttingIssue;
  }


}

