package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 2, 2016 11:02:00 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Submission generated by hbm2java
 */
public class Submission implements java.io.Serializable {

  private static final long serialVersionUID = 7498387276775729842L;


  private Long id;


  private User user;


  private ResearchCycle researchCycle;


  private ResearchProgram researchProgram;


  private Date dateTime;


  private String modificationJustification;


  private Short year;


  public Submission() {
  }


  public Submission(User user, Date dateTime) {
    this.user = user;
    this.dateTime = dateTime;
  }


  public Submission(User user, ResearchCycle researchCycle, ResearchProgram researchProgram, Date dateTime,
    String modificationJustification, Short year) {
    this.user = user;
    this.researchCycle = researchCycle;
    this.researchProgram = researchProgram;
    this.dateTime = dateTime;
    this.modificationJustification = modificationJustification;
    this.year = year;
  }


  public Date getDateTime() {
    return dateTime;
  }


  public Long getId() {
    return id;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public ResearchCycle getResearchCycle() {
    return researchCycle;
  }

  public ResearchProgram getResearchProgram() {
    return researchProgram;
  }

  public User getUser() {
    return user;
  }

  public Short getYear() {
    return year;
  }

  public void setDateTime(Date dateTime) {
    this.dateTime = dateTime;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setResearchCycle(ResearchCycle researchCycle) {
    this.researchCycle = researchCycle;
  }

  public void setResearchProgram(ResearchProgram researchProgram) {
    this.researchProgram = researchProgram;
  }


  public void setUser(User user) {
    this.user = user;
  }

  public void setYear(Short year) {
    this.year = year;
  }

}

