INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchProgram', 'climate');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchProgram', 'ecosystem');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchProgram', 'markets');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchLeader', 'Program Coordination');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchLeader', 'Research Area Leader');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchLeader', 'Research Program Leader');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchObjective', 'Strategic Objective');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchObjective', 'Research Area Objective');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchPartner', 'Internal Partner');
INSERT INTO `all_types` (`class_name`, `type_name`) VALUES ('ResearchPartner', 'External Partner');